- id: '1601206498993'
  alias: webhook
  description: ''
  trigger:
  - platform: webhook
    webhook_id: parsehub_library
  condition: []
  action:
  - service: persistent_notification.create
    data:
      message: '{{ trigger.data.status }}

        {{ trigger.data.run_token }}

        {{ (trigger.data.start_value | from_json).entity_id }}


        {{ trigger.data }}

        '
  - service: shell_command.library_get
    data:
      friendly_name: '{%- set start_value = trigger.data.start_value | from_json %}
        {{ start_value.mail }}'
      entity_id: '{%- set start_value = trigger.data.start_value | from_json %} {{
        start_value.name }}'
  mode: single
