################################################################################
#                       __                    __                               #
#                      / /   ____ _   _____  / /___ _________                  #
#                     / /   / __ \ | / / _ \/ / __ `/ ___/ _ \                 #
#                    / /___/ /_/ / |/ /  __/ / /_/ / /__/  __/                 #
#                   /_____/\____/|___/\___/_/\__,_/\___/\___/                  #
#                                                 by J-Lindvig                 #
################################################################################
# Created: 23/10/2020                                                          #
################################################################################

custom_header:
  locale: da-DK
  compact_mode: True
  
title: Skovtrolden

views:
  - !include views/main.yaml
  - !include views/room_lights.yaml
  - !include views/movies.yaml
  - !include views/light_control.yaml
  - !include views/system.yaml
  - !include views/gauges.yaml
  - !include views/weather.yaml
  - !include views/test.yaml

################################################################################
####                              End of file                               ####
################################################################################