- alias: Pengekasse
  id: 5e0451e75b584632814674caa9a5d38b
  description: "Pengekassen er blevet åbnet"
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.pengekasse
      from: "off"
  action:
    - service: notify.mobile_app_jacobs_moto
      data:
        title: "OBS"
        message: "Pengekassen er blevet åbnet"
        data:
          channel: Pengekasse
          importance: high